name: '접수인원 보고 이슈 등록하기'

on:
  schedule:
    - cron: '* * * * *'
    #- cron: '5 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install beautifulsoup4
        pip install pytz
        pip install PyGithub
        pip install python-dateutil
    - name: Run Crawler
      run: |
        python koreatt.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}